version: '3'
services:
  devian:
    build: .
    container_name: dRail
    ports:
      - 5000:5000
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.drail.entrypoints: websecure
      traefik.http.routers.drail.tls: true
      traefik.http.routers.drail.rule: (Host(`centricity.telinduscloud.lu`) && PathPrefix(`/drail`))
      traefik.http.services.drail.loadbalancer.server.port: 5000
    
networks:
  default:
    name: traefik_network
    external: true